using BadDeduction.Core;

namespace BadDeduction.Police;

/// <summary>How hot the city is. Rises with unsolved violence, falls when cases close.</summary>
public enum AlertLevel
{
    Calm,
    Alert,
    Manhunt,
}

/// <summary>What an officer is assigned to do during work hours.</summary>
public enum DutyKind
{
    /// <summary>Stand watch at a sealed crime scene (the cordon).</summary>
    Guard,
    /// <summary>Walk a beat through public locations.</summary>
    Patrol,
    /// <summary>Case work at the officer's station.</summary>
    Investigate,
}

/// <summary>Minimal case lifecycle. Full win/lose and trial outcomes are out of scope (audit §D).</summary>
public enum CaseState
{
    Open,
    PersonOfInterest,
    InCustody,
}

/// <summary>One officer's assignment for one day. Plain data.</summary>
public sealed class DutyAssignment
{
    public string OfficerId { get; set; } = "";
    public int Day { get; set; }
    public DutyKind Kind { get; set; }
    public string LocationId { get; set; } = "";
    /// <summary>Set for Guard duties: the scene being watched.</summary>
    public string? SceneId { get; set; }
}

/// <summary>Minimal per-crime case status. Plain data; mutated only by PoliceService.</summary>
public sealed class CaseStatus
{
    public CaseState State { get; set; } = CaseState.Open;
    /// <summary>Person of interest or detainee, when State is not Open.</summary>
    public string? SubjectId { get; set; }
}

/// <summary>
/// Phase 9: the police subsystem's plain-data state. Mutated only by PoliceService.
/// Per-officer RNG streams are derived lazily from the run seed ("police.{officerId}"),
/// so they are order-independent and survive save/load by construction.
/// </summary>
public sealed class PoliceState
{
    public AlertLevel Alert { get; set; } = AlertLevel.Calm;

    /// <summary>Persisted per-officer streams, used only for tie-breaks and patrol choices — never for facts.</summary>
    public Dictionary<string, RngState> OfficerRng { get; set; } = new();

    /// <summary>Today's duty roster, keyed by officer id. Regenerated by AssignDuties().</summary>
    public Dictionary<string, List<DutyAssignment>> Duties { get; set; } = new();

    /// <summary>Which day <see cref="Duties"/> was assigned for. 0 means "never assigned".</summary>
    public int DutiesDay { get; set; }

    /// <summary>Minimal case lifecycle per crime id.</summary>
    public Dictionary<string, CaseStatus> Cases { get; set; } = new();

    /// <summary>
    /// Phase 13: disturbance reports (e.g. death threats made in public). Plain data;
    /// appended only by <see cref="PoliceService.ReportDisturbance"/>. Two recent severe
    /// reports can step the alert ladder to Alert — never to Manhunt (ADR-048).
    /// </summary>
    public List<DisturbanceReport> Disturbances { get; set; } = new();
}

/// <summary>Phase 13: one reported disturbance — who caused it, where, how severe, when.</summary>
public sealed class DisturbanceReport
{
    public long Timestamp { get; set; }
    public string LocationId { get; set; } = "";
    public string SubjectId { get; set; } = "";
    public int Severity { get; set; }
}
